import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar, Sidebar } from "@/components";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-white min-h-screen max-h-screen overflow-scroll w-full">
          <Sidebar/>
          <div className="content w-full h-full">
            <Navbar/>
            <div className="p-6 pt-8">
              <div className="text-sm breadcrumbs mb-6">
                <ul>
                  <li><a>Home</a></li> 
                  <li><a>Documents</a></li> 
                  <li>Add Document</li>
                </ul>
              </div>
              
              {children}
              
            </div>
          </div>
        </div>
        <ToastContainer/>
      </body>
    </html>
  );
}
