import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar, Sidebar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-white min-h-screen w-full">
          <Sidebar/>
          <div className="content w-full">
            <Navbar/>
            <div className="p-6 pt-8">
            <div className="text-sm breadcrumbs mb-6">
              <ul>
                <li><a>Home</a></li> 
                <li><a>Documents</a></li> 
                <li>Add Document</li>
              </ul>
            </div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
